### ISSUE TITLE
烈士来报到了

### ISSUE THREAD

**Issue by ywgdjryf** [ramoncjs3/HerosEvil#1]
仿照着改写了一个自动打告示牌的脚本, 二轮罕有的大号直接就没了, 
![image](https://github.com/ramoncjs3/HerosEvil/assets/149993388/c8d2bbf6-167c-4ff7-8322-97b1a2fdebbd)

问客服, 客服安了一个**非法修改游戏数据**的罪名到我头上.
抓包发包的代码 还是碰不得的.

**Comment by ramoncjs3** [comment]
你这直接刷任务多少是有些过分了，从收益上来看，此举直接降低了用户粘性，降低用户在线，必须打击啊....

**Comment by ykjsj** [comment]
应该是你发的包数据有问题把，包数据都是需要本地运算的，违法数据肯定是不行的啊
